# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_dominates_expect <- function(x, y, tol) {
    .Call('_murphydiagram2_C_dominates_expect', PACKAGE = 'murphydiagram2', x, y, tol)
}

C_dominates_quant <- function(x, y, tol) {
    .Call('_murphydiagram2_C_dominates_quant', PACKAGE = 'murphydiagram2', x, y, tol)
}

C_md_expect <- function(x, y, level, ordery) {
    .Call('_murphydiagram2_C_md_expect', PACKAGE = 'murphydiagram2', x, y, level, ordery)
}

C_md_quant <- function(x, y, level, ordery) {
    .Call('_murphydiagram2_C_md_quant', PACKAGE = 'murphydiagram2', x, y, level, ordery)
}

C_thin_by <- function(x, y, xtol, ytol) {
    .Call('_murphydiagram2_C_thin_by', PACKAGE = 'murphydiagram2', x, y, xtol, ytol)
}

